- .github/workflows/buildDebug.yml
- .github/workflows/buildRelease.yml
- .idea/misc.xml
- README.md
- app/build.gradle.kts
- build.gradle.kts
- gradle.properties
Some build scripts (#21)
Merge pull request #22 from DerTyp7214/master
Translations
README.md
README.md
gradle update
* c1d0a9c - Josua Lengwenath - 2021-10-20 05:56:40 
| gradle update
| 
* 08330a0 - Josua Lengwenath - 2021-10-20 05:29:35 
README.md
* c58bd50 - Josua Lengwenath - 2021-10-20 05:35:55 
| README.md
| 
* d2b885f - DerBot7214 - 2021-10-20 05:19:58 
| Translations
| translations
* 692a76e - DerBot7214 - 2021-10-20 05:00:41 
| Merge pull request #22 from DerTyp7214/master
| Fix commit history
* 8c12baa - github-actions[bot] - 2021-10-20 04:59:04 
Some build scripts (#21)
* create pull request on push
* typo 🙂
* 🙂🦄
* 🦄
* 🦄🙂🙃
* use custom template
* cleanup some actions
* remove pull request event typo on test build
* Some build scripts
* create pull request on push
* Some build …
> gradle update

- .github/workflows/buildDebug.yml
- .github/workflows/buildRelease.yml
- .github/workflows/createTranslationPullRequest.yml
- .idea/misc.xml
- README.md
- app/build.gradle.kts
- build.gradle.kts
- gradle.properties
Some build scripts (#21)
Merge pull request #22 from DerTyp7214/master
Translations
README.md
README.md
gradle update
gradle update
bump buildTools version
translation pull request
* 90c6107 - Josua Lengwenath - 2021-10-20 11:40:04 
| translation pull request
| 
* 582acee - Josua Lengwenath - 2021-10-20 09:27:06 
| bump buildTools version
| 
* c1d0a9c - Josua Lengwenath - 2021-10-20 05:56:40 
| gradle update
| 
* 08330a0 - Josua Lengwenath - 2021-10-20 05:29:35 
README.md
* 71b97af - Josua Lengwenath - 2021-10-20 06:03:45 
| gradle update
| 
* c58bd50 - Josua Lengwenath - 2021-10-20 05:35:55 
| README.md
| 
* d2b885f - DerBot7214 - 2021-10-20 05:19:58 
| Translations
| translations
* 692a76e - DerBot7214 - 2021-10-20 05:00:41 
| Merge pull request #22 from DerTyp7214/master
| Fix commit …
> bump buildTools version

- .github/workflows/buildRCompatible.yml
- .github/workflows/createTranslationPullRequest.yml
Merge pull request #28 from DerTyp7214/rCompatible
Merge pull request #29 from DerTyp7214/rCompatible
Merge pull request #30 from DerTyp7214/rCompatible
Update Hungarian translation
update buildTools Version 🐦
* a2adaa1 - Akos Paha - 2021-10-20 16:46:25 
update buildTools Version 🐦
* 29a2c5a - Akos Paha - 2021-10-20 09:08:34 
| Update Hungarian translation
| 
* bbf8588 - Akos Paha - 2021-10-20 08:51:05 
| Merge pull request #30 from DerTyp7214/rCompatible
| Update buildRCompatible.yml
* 44cc1b3 - Akos Paha - 2021-10-20 08:44:37 
| Merge pull request #29 from DerTyp7214/rCompatible
| Revert Update
* ab5b269 - Akos Paha - 2021-10-20 08:39:00 
Merge pull request #28 from DerTyp7214/rCompatible
Update pullRequest.yml
.github/workflows/buildRCompatible.yml             |  2 +- …
> update buildTools Version 🐦

- app/build.gradle.kts
- app/src/main/java/de/dertyp7214/rboardthememanager/core/Map.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/preferences/Flags.kt
- app/src/main/res/drawable/ic_keyboard_height.xml
- app/src/main/res/raw/flags.json
- app/src/main/res/values/strings.xml
Gradle Update
height ratio selection
keyboard height
whoops
* a409261 - Josua Lengwenath - 2021-11-04 21:03:25 
| whoops
| 
* a3cde1a - Josua Lengwenath - 2021-11-04 21:02:08 
| keyboard height
| 
* 3993659 - Josua Lengwenath - 2021-11-04 03:05:08 
height ratio selection
* e2abf7f - DerBot7214 - 2021-10-30 20:01:09 
Gradle Update
merged #53 
app/build.gradle.kts                               |  4 +-
.../de/dertyp7214/rboardthememanager/core/Map.kt   |  6 ++
.../rboardthememanager/preferences/Flags.kt        | 32 +++++++--
.../main/res/drawable/ic_keyboard_height.xml (new) | 15 ++++
app/src/main/res/raw/flags.json                    | 80 +++++++++++++++++++++-
app/src/main/res/values/strings.xml                | 12 ++++
6 files changed, 141 insertions(+), 8 deletions(-)
> height ratio selection

- app/src/main/res/values-it/strings.xml
> translation updated

- app/src/main/res/values-it/strings.xml
Reverts DerTyp7214/RboardThemeManagerV3#59
> Revert "translation updated"

- .github/workflows/buildRelease.yml
- .github/workflows/deployToGoogle.yml
- app/build.gradle.kts
Merge pull request #72 from DerTyp7214/master
Update Italian translation
small bug and translation fixes
small bug and translation fixes
small bug and translation fixes
cleanup
lib updates, reworked flags
accept sdk license 🙃
* 5c27b5b - DerBot7214 - 2022-03-10 20:35:30 
accept sdk license 🙃
* f795ee2 - DerBot7214 - 2022-03-10 20:18:51 
| lib updates, reworked flags
| Merge pull request #96 from DerTyp7214/master
* ed50f89 - DerBot7214 - 2022-01-30 23:10:32 
| cleanup
| Merge pull request #94 from DerTyp7214/master
* 370bc8c - DerBot7214 - 2022-01-28 04:31:49 
| small bug and translation fixes
| Merge pull request #93 from DerTyp7214/master
* 5b52fd8 - DerBot7214 - 2022-01-28 04:29:27 
| small bug and translation fixes
| Merge pull request #92 from DerTyp7214/master
* a123423 - DerBot7214 …
> accept sdk license 🙃

- .idea/misc.xml
- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/de/dertyp7214/rboardthememanager/preferences/Settings.kt
- app/src/main/res/layout/activity_preferences.xml
- app/src/main/res/raw/flags.json
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-night-v27/themes.xml
- app/src/main/res/values-night-v30/themes.xml
- app/src/main/res/values-night-v31/colors.xml
- app/src/main/res/values-night-v31/themes.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values-v27/themes.xml
- app/src/main/res/values-v30/themes.xml
- app/src/main/res/values-v31/colors.xml
- app/src/main/res/values-v31/themes.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
- build.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Add Initial Support For Android 6 and 7.x (Test), Props, deeplinking, viewmodel fix, Gradle and translation update
Props fix
New buildscript
Fix app update install on Android M/N (Android 6-7.x download this update manually), performance (logging)
Update BuildScript, Fix app update on Android M/N (Hopefully permanently)
Include theme names and file size in download tab, Update README.md
Update README.md
Merge pull request #75 from DerTyp7214/rCompatible-Dev
Merge pull request #77 from DerTyp7214/rCompatible-Dev
Merge pull request #79 from DerTyp7214/rCompatible-Dev
Update Italian 
Add Initial Support For Android 6 and 7.x (Test), Props, deeplinking, viewmodel fix, Gradle and translation update
Props fix
New buildscript
Fix app update install on Android M/N (Android 6-7.x download this …
> Add Collapsing action bar, Add options to clear the cache and recent emojis, Grammar fix, bump version to 3.4.7

- .idea/misc.xml
- app/build.gradle.kts
- app/src/main/java/de/dertyp7214/rboardthememanager/Config.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/core/SoundPack.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/screens/MainActivity.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/utils/AppStartUp.kt
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Add Initial Support For Android 6 and 7.x (Test), Props, deeplinking, viewmodel fix, Gradle and translation update
Props fix
New buildscript
Fix app update install on Android M/N (Android 6-7.x download this update manually), performance (logging)
Update BuildScript, Fix app update on Android M/N (Hopefully permanently)
Include theme names and file size in download tab, Update README.md
Update README.md
Merge pull request #75 from DerTyp7214/rCompatible-Dev
Merge pull request #77 from DerTyp7214/rCompatible-Dev
Merge pull request #79 from DerTyp7214/rCompatible-Dev
Update Italian 
Add Initial Support For Android 6 and 7.x (Test), Props, deeplinking, viewmodel fix, Gradle and translation update
Props fix
New buildscript
Fix app update install on Android M/N (Android 6-7.x download this …
> Update dependencies, Fix sounds and theme import for old Androids

- app/src/main/res/values-it/strings.xml
> Update Italian Translation

- .idea/misc.xml
- app/build.gradle.kts
- app/src/main/java/de/dertyp7214/rboardthememanager/components/XMLFile.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/core/Activity.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/core/File.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/core/TextInputLayout.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/preferences/Flags.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/screens/ShareFlags.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/utils/AppStartUp.kt
- app/src/main/res/drawable/menu_down.xml
- app/src/main/res/layout/xml_entry_dialog_layout.xml
- app/src/main/res/menu/all_prefs.xml
- app/src/main/res/menu/flags_add.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
version bump, lib updates, back handling changes, new flags
version bump, lib updates, back handling changes, new flags
version bump, lib updates, back handling changes, new flags
version bump, lib updates, back handling changes, new flags
version bump, lib updates, back handling changes, new flags
Update strings.xml
version bump, lib updates, back handling changes, new flags
whoops
magisk stuff
Merge branch 'staging' into master
lifecycle fix, flags fix
Merge branch 'staging' into master
lifecycle fix, flags fix
Merge branch 'master' of github.com:DerTyp7214/RboardThemeManagerV3
Update Italian strings.xml (#118)
custom flags and prefs input, import and share prefs
* ab9d0bb - DerBot7214 - 2022-05-25 02:29:59 
| custom flags and prefs input, import and share prefs
| 
* 5dfa564 - Alpha - …
> Update Italian strings.xml (#118)

- app/build.gradle.kts
- app/src/main/java/de/dertyp7214/rboardthememanager/components/SearchBar.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/components/SearchToolbar.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/core/Activity.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/core/View.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/screens/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/search_bar.xml
- app/src/main/res/layout/search_toolbar.xml
- app/src/main/res/values/attrs.xml
chrome custom tab color fix
new searchToolbar
update cmake
* 48f3de1 - DerBot7214 - 2022-08-21 23:22:09 
| update cmake
| 
* 3bdfde9 - DerBot7214 - 2022-08-21 23:15:30 
| new searchToolbar
| 
* 1985983 - DerBot7214 - 2022-08-19 09:28:04 
chrome custom tab color fix
app/build.gradle.kts                               |  13 +-
.../rboardthememanager/components/SearchBar.kt     |   4 +-
.../components/SearchToolbar.kt (new)              | 175 +++++++++++++++++++++
.../dertyp7214/rboardthememanager/core/Activity.kt |   9 +-
.../de/dertyp7214/rboardthememanager/core/View.kt  |  19 +--
.../rboardthememanager/screens/MainActivity.kt     |  34 ++--
app/src/main/res/layout/activity_main.xml          |  30 ++--
app/src/main/res/layout/search_bar.xml             | 144 +++++++++-------- …
> chrome custom tab color fix

- .github/workflows/buildCi.yml
- .idea/kotlinc.xml
- app/build.gradle.kts
- app/src/main/java/de/dertyp7214/rboardthememanager/screens/MainActivity.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/utils/AppStartUp.kt
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Fix download count reset after update
Update Gradle
Update Kotlin
Merge pull request #183 from DerTyp7214/rCompatible-Dev-Update
* b45ed7f - Akos Paha - 2022-12-11 11:28:30 
| Merge pull request #183 from DerTyp7214/rCompatible-Dev-Update
|  Fix download count reset after update
* 980a664 - AkosPaha - 2022-12-11 11:18:12 
| Update Kotlin
| 
* 4c54fbb - AkosPaha - 2022-12-11 11:15:57 
| Update Gradle
| 
* 9bb189c - AkosPaha - 2022-12-11 11:07:02 
Fix download count reset after update
.github/workflows/buildCi.yml                      |  6 +++---
.idea/kotlinc.xml                                  |  2 +-
app/build.gradle.kts                               | 24 +++++++++++-----------
.../rboardthememanager/screens/MainActivity.kt     | 17 +++++++-------- …
> Fix download count reset after update

- .github/workflows/buildCi.yml
- .github/workflows/buildRelease.yml
- .github/workflows/pullRequest.yml
- README.md
readme and actions update
readme
Update README.md
* 08fbdba - DerBot7214 - 2022-12-11 19:05:23 
| Update README.md
| 
* 4fff34a - DerBot7214 - 2022-12-11 18:56:30 
| readme
| 
* a5029d3 - DerBot7214 - 2022-12-11 18:55:02 
readme and actions update
.github/workflows/buildCi.yml      | 4 ++--
.github/workflows/buildRelease.yml | 4 ++--
.github/workflows/pullRequest.yml  | 4 ++--
README.md                          | 4 +++-
4 files changed, 9 insertions(+), 7 deletions(-)
> readme and actions update

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/de/dertyp7214/rboardthememanager/preferences/Repos.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/screens/InstallPackActivity.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/screens/MainActivity.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/utils/AppStartUp.kt
fix download of update and request notification permissions
* c5974c6 - DerBot7214 - 2022-12-11 22:28:10 
fix download of update and request notification permissions
app/build.gradle.kts                               |  4 +-
app/src/main/AndroidManifest.xml                   |  7 +++-
.../rboardthememanager/preferences/Repos.kt        | 28 +++++++-------
.../screens/InstallPackActivity.kt                 | 10 +++--
.../rboardthememanager/screens/MainActivity.kt     | 11 ++++--
.../rboardthememanager/utils/AppStartUp.kt         | 44 ++++++++++++++++------
6 files changed, 66 insertions(+), 38 deletions(-)
> fix download of update and request notification permissions

- app/build.gradle.kts
- app/src/main/java/de/dertyp7214/rboardthememanager/Application.kt
- app/src/main/res/xml/locale_config.xml
fix languages
* d800df6 - DerBot7214 - 2022-12-13 22:44:40 
fix languages
app/build.gradle.kts                                             | 9 +++++----
.../main/java/de/dertyp7214/rboardthememanager/Application.kt    | 2 ++
app/src/main/res/xml/locale_config.xml                           | 2 +-
3 files changed, 8 insertions(+), 5 deletions(-)
> fix languages

- .github/workflows/buildCi.yml
- .idea/kotlinc.xml
- app/build.gradle.kts
- build.gradle.kts
- com.google.devtools.ksp to 1.9.0-1.0.11 
- androidx.navigation:navigation-fragment-ktx to 2.7.0-beta02
- androidx.navigation:navigation-ui-ktx to 2.7.0-beta02
- org.jetbrains.kotlin:kotlin-stdlib to 1.9.0
- com.google.android.material:material to 1.11.0-alpha01
- androidx.activity:activity-ktx to 1.8.0-alpha06
- androidx.browser:browser to 1.6.0-beta01
- androidx.compose.ui:ui-tooling to 1.5.0-beta03
- org.jetbrains.kotlin:kotlin-reflect to 1.9.0
- com.android.tools.build:gradle to 8.2.0-alpha10
- kotlin(gradle-plugin) to 1.9.0
- KotlinJpsPluginSettings to 1.9.0
- gradle/gradle-build-action to 2.5.1
> Update Libs, Kotlinc, Workflow file

- .idea/gradle.xml
- .idea/migrations.xml
- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
New dependency changes:
• com.android.tools.build:gradle to 8.2.0-alpha12
• com.google.firebase:firebase-bom to 32.2.0
> Switch to new library catalog declaration

- .github/workflows/buildCi.yml
- .github/workflows/buildPro.yml
- .github/workflows/pullRequest.yml
- .idea/compiler.xml
- .idea/gradle.xml
- .idea/kotlinc.xml
- .idea/misc.xml
- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
New changes:
• Bump App Version to 3.8.4
• Update Java Version to 20
• Move com.google.devtools.ksp to libs.versions.toml file
> App & Java Version Update

- .idea/compiler.xml
- .idea/kotlinc.xml
- .idea/misc.xml
> Java Version Correction

- .github/workflows/buildCi.yml
- .github/workflows/buildPro.yml
- .github/workflows/pullRequest.yml
- .idea/misc.xml
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
New dependencies changes:
• androidx.appcompat:appcompat to 1.7.0-alpha03
• androidx.browser:browser to 1.6.0-rc01
• androidx.constraintlayout:constraintlayout to 2.2.0-alpha11 • androidx.core:core-ktx to 1.12.0-beta01
• androidx.core:core to 1.12.0-beta01
• androidx.compose.ui:ui-tooling to 1.6.0-alpha02
• androidx.lifecycle:lifecycle-viewmodel-ktx to 2.7.0-alpha01 • androidx.navigation:navigation-fragment-ktx to 2.7.0-rc01 • androidx.navigation:navigation-ui-ktx to 2.7.0-rc01 • com.android.tools.build:gradle to 8.2.0-alpha14
• com.github.topjohnwu.libsu:io to 5.2.0
• com.google.devtools.ksp to 1.9.0-1.0.12
New workflow changes:
• actions/setup-java to 3.12.0
• gradle/gradle-build-action to 2.7.0
> //Update dependencies and Workflow files//

- app/build.gradle.kts
New changes:
• Bump versionCode to 384001
> App Version Update

- app/build.gradle.kts
- gradle/libs.versions.toml
New Dependencies changes:
• Add com.android.tools:desugar_jdk_libs 2.0.3
> Java 8+ APIs through desugaring

- app/build.gradle.kts
- app/src/main/java/de/dertyp7214/rboardthememanager/preferences/Props.kt
- app/src/main/res/drawable/ic_kbp_fland_b.xml
- app/src/main/res/drawable/ic_kbp_fland_l.xml
- app/src/main/res/drawable/ic_kbp_fland_r.xml
- app/src/main/res/drawable/ic_kbp_fport_b.xml
- app/src/main/res/drawable/ic_kbp_fport_l.xml
- app/src/main/res/drawable/ic_kbp_fport_r.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-land/bool.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-sw600dp-land/bools.xml
- app/src/main/res/values-sw600dp/bools.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/bools.xml
- app/src/main/res/values/strings.xml
Others Changes:
• Update versionName to 3.8.7
• Update versionCode to 387001
• Update Translations
> Add foldable margin for large display devices

- .idea/misc.xml
- app/build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
New App Themes:
• Amoled
• Apocyan
• Brown Blue
• Monochrome
• Lavender Tonic
• Peach Pearl
• Samoan Sun
• Yellow Purple
Others Changes:
• Update versionName to 3.9.1
• Update versionCode to 391001
> Bump VersionName to 3.9.1, Add New App Themes, Update Subs

- app/build.gradle.kts
Others Changes:
• Update versionCode to 391003
> Update existing app themes

- .idea/misc.xml
- app/build.gradle.kts
New App Themes:
• Mud Pink
• Vert Pierre
Others Changes:
• Update versionCode to 391005
> Add 2 New App Themes, Bump VersionCode to 391005

- app/build.gradle.kts
- app/src/main/java/de/dertyp7214/rboardthememanager/utils/GboardUtils.kt
🗂️ Others Changes:
• Fix Type Mismatch
• Update versionCode to 392007 (3.9.2)
>  Debug Release 3.9.2 (392007)

- .idea/vcs.xml
- app/build.gradle.kts
Reverts DerTyp7214/RboardThemeManagerV3#961
> Revert "Update vcs"

- app/build.gradle.kts
- app/src/main/java/de/dertyp7214/rboardthememanager/preferences/Settings.kt
- app/src/main/java/de/dertyp7214/rboardthememanager/utils/AppStartUp.kt
- app/src/main/res/values-pt-rBR/strings.xml
- gradle/libs.versions.toml
🚀 Release 3.9.4 (394000)
🚀 Release 3.9.4 (394000)
🚀 Release 3.9.5 (395000)
🚀 Release 3.9.5 (395005)
🚀 Release 3.9.5 (395005)
Copy Flags Fix
Merge pull request #986 from DerTyp7214/rComp-Copy-Flags-Fix
* b4d8492a - Akos Paha - 2025-07-11 13:58:22 
| Merge pull request #986 from DerTyp7214/rComp-Copy-Flags-Fix
| Copy Flags Fix
| 
| • Bump versionCode to 395006 (3.9.5)
| • Delete llm_pc_gemma_prompt_tag_end value when copying a flag to fix flag loading
| • Update portuguese translation
* f935c812 - PahaAkos - 2025-07-11 13:40:55 
Copy Flags Fix
• Bump versionCode to 395006 (3.9.5)
• Delete llm_pc_gemma_prompt_tag_end value when copying a flag to fix flag loading
• Update portuguese translation
* c39a472f - Akos Paha - 2025-07-03 17:26:18 
| 🚀 Release 3.9.5 (395005)
| • Add Repo URL copy …
> Copy Flags Fix

- .github/workflows/buildRelease.yml
- app/build.gradle.kts
🚀 Release 3.9.5 (395005)
Merge pull request #989 from DerTyp7214/master
Workflow edit
Bump Version to 3.9.5 (395008)
Bump Version to 3.9.5 (395008)
* 3d45fb53 - Akos Paha - 2025-07-13 14:10:23 
| Bump Version to 3.9.5 (395008)
| • Fix workflow
| • Bump Version to 3.9.5 (395008)
* 4f88c689 - Akos Paha - 2025-07-13 14:04:15 
Bump Version to 3.9.5 (395008)
* 0fa20f2d - Akos Paha - 2025-07-13 13:55:30 
| Workflow edit
| 
* 02b830a9 - Akos Paha - 2025-07-11 14:09:26 
| Merge pull request #989 from DerTyp7214/master
| Copy Flags Fix
| 
| • Bump versionCode to 395006 (3.9.5)
| • Delete llm_pc_gemma_prompt_tag_end value when copying a flag to fix flag loading 
| • Update portuguese translation
* 368f29d3 - Akos Paha - 2025-07-03 16:33:36 
🚀 Release 3.9.5 (395005)
• Add Repo URL copy option
• Bump …
> Bump Version to 3.9.5 (395008)
